src/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('list/', projects, name='project-list')
]

src/management/urls.py
from django.urls import path
from .views import *

app_name = 'management'

urlpatterns = [
    path('', index, name='management-view'),
    path('create/', create, name='management-create'),
    path('delete/<int:id>', delete, name='management-delete'),
    path('update/<int:id>', update, name='management-update'),
]

src/website_development_portfolio/urls.py
""" Routes """

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='landing'),
    path('projects/', include('main.urls')),
    path('policies/', include('extra.urls')),
    path('management/', include('management.urls'))
]

# Static and media files routing
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "extra.views.page_not_found"
handler500 = "extra.views.server_error"

src/management/models.py
from django.db import models

# Create your models here.

src/management/forms.py
from django import forms
from main.models import Project


class ProjectForm(forms.ModelForm):
    project_name = forms.CharField(
        required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Example Site 1'}), label='Project Name')
    project_description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}), label='Project Description')
    project_picture = forms.ImageField(
        widget=forms.FileInput(attrs={'class': 'custom-file-input'}), label='Project Picture', required=False)
    project_url = forms.URLField(
        required=True, widget=forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://www.github.com'}), label='Source Code Link')
    author = forms.CharField(
        required=True, label='Project Author', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'MyAwesomeUsername'}))
    author_email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'contact@me.com'}), label='Author email')
    extra_information = forms.FileField(widget=forms.FileInput(
        attrs={'class': 'custom-file-input'}), label='More Information File', required=False)
    is_in_progess = forms.BooleanField(label='Done', required=False)

    class Meta:
        model = Project
        fields = '__all__'

src/management/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import ProjectForm
from main.models import Project
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage


@login_required
def index(request):
    project_list = Project.objects.all().order_by('-posted_at')
    page = request.GET.get('page', 1)
    paginator = Paginator(project_list, 4)

    number_of_results = paginator.count

    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        projects = paginator.page(1)
    except EmptyPage:
        projects = paginator.page(paginator.num_pages)

    if not project_list:
        empty = True
    elif project_list:
        empty = False

    context = {
        'posts': projects,
        'num_of_results': number_of_results,
        'empty': empty
    }
    return render(request, 'management/index.html', context)


@login_required
def create(request):
    form = ProjectForm(request.POST or None, request.FILES or None)

    if request.method == "POST":
        form = ProjectForm(request.POST or None, request.FILES or None)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect('/management/')

    context = {
        'form': form
    }
    return render(request, 'management/create.html', context)


@login_required
def delete(request, id):
    project = Project.objects.get(id=id)
    project.delete()

    return HttpResponseRedirect('/management/')


@login_required
def update(request, id):
    project = Project.objects.get(id=id)
    form = ProjectForm(request.POST or None,
                       request.FILES or None, instance=project)

    if request.method == "POST":
        form = ProjectForm(request.POST or None,
                           request.FILES or None, instance=project)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect('/management/')

    context = {
        'form': form
    }
    return render(request, 'management/update.html', context)

src/management/templates/management/create.html
{% extends 'shared/base.html' %}

{% block title %}Management{% endblock title %}

{% block body %}
<!-- Main content -->
<main>
    <!-- Create form section -->
    <section class="container-fluid">
        <div class="container">
            <!-- Heading -->
            <h1 class="display-4 text-center">Create</h1>

            <!-- Division -->
            <hr class="border-dark w-50">

            <!-- Create Form -->
            <form action="{% url 'management:management-create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6">
                        <div class="lead">{{ form.project_name.label }}</div>
                        <div class="pb-1"></div>
                        {{ form.project_name }}
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.project_url.label }}</div>
                        <div class="pb-1"></div>
                        {{ form.project_url }}
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.author.label }}</div>
                        <div class="pb-1"></div>
                        {{ form.author }}
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.author_email.label }}</div>
                        <div class="pb-1"></div>
                        {{ form.author_email }}
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.is_in_progress.label }}</div>
                        <div class="pb-1"></div>
                        <div class="card">
                            <div class="card-body">{{ form.is_in_progess }} <span class="text-info">Are you done with
                                    the project</span></div>
                        </div>
                        <div class="pb-1"></div>
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-primary w-100 mt-2"><i
                                        class="fa fa-plus-circle"></i> Create</button>
                            </div>
                            <div class="col-6">
                                <button type="reset" class="btn btn-warning w-100 mt-2"><i class="fa fa-recycle"></i>
                                    Reset</button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <p class="text-center mt-1"><a href="{% url 'management:management-view' %}"
                                        class="btn-link">&leftarrow; Go to the dashboard</a></p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <span class="lead">{{ form.project_picture.label }}</span>
                        <div class="pb-1"></div>
                        <div class="custom-file">
                            {{ form.project_picture }}
                            <label class="custom-file-label">Select only 1 file</label>
                        </div>
                        <div class="pb-1"></div>

                        <span class="lead">{{ form.extra_information.label }}</span>
                        <div class="pb-1"></div>
                        <div class="custom-file">
                            {{ form.extra_information }}
                            <label class="custom-file-label">Optional, select only 1 file</label>
                        </div>
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.project_description.label }}</div>
                        {{ form.project_description }}
                    </div>
                </div>
            </form>
        </div>
    </section>
</main>
{% endblock body %}

src/management/templates/management/index.html
{% extends 'shared/base.html' %}

{% block title %}Management{% endblock title %}

{% block inline_css %}
<style>
    .cursor {
        cursor: pointer;
    }

    .default-cursor {
        cursor: default;
    }
</style>
{% endblock inline_css %}

{% block body %}
{% include 'shared/components/navbar2.html' %}

<!-- Main content -->
<main>
    <!-- Listing section -->
    <section class="container-fluid">
        <div class="container">
            <!-- Header -->
            <h1 class="display-4 text-center">Listing</h1>

            <!-- Divider -->
            <hr class="border-dark w-50">
            {% if not empty %}

            <!-- Objects table -->
            <table class="table table-bordered">
                <tbody>
                    {% for post in posts %}
                    <tr>
                        <td>{{ post }}</td>
                        <td><a href="{% url 'management:management-update' post.id %}"><button
                                    class="btn btn-primary float-right">Update</button></a></td>
                        <td><a href="{% url 'management:management-delete' post.id %}"><button
                                    class="btn btn-danger float-right">Delete</button></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}

            <!-- Message -->
            <p class="text-center lead"><code>Sorry no query object posted</code></p>
            {% endif %}

            <!-- Information Card -->
            <div class="card bg-primary">
                <div class="card-body text-white text-right">
                    <h5>Query objects posted are <code>{{ num_of_results }}</code></h5>
                </div>
            </div>

            {% if posts.has_other_pages %}
            <!-- Pagination -->
            <ul class="pagination justify-content-center mt-2">
                {% if posts.has_previous %}
                <li class="page-item default-cursor"><a href="?page={{ posts.previous_page_number }}"
                        class="page-link">&laquo;</a></li>
                {% else %}
                <li class="disabled page-item page-link"><span>&laquo;</span></li>
                {% endif %}
                {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                <li class="active page-item page-link cursor"><span>{{ i }} <span
                            class="sr-only">(current)</span></span>
                </li>
                {% else %}
                <li class="page-item cursor"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                <li class="page-item cursor"><a href="?page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
                </li>
                {% else %}
                <li class="disabled page-item page-link default-cursor"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </section>
</main>

{% include 'shared/components/footer2.html' %}
{% endblock body %}

src/management/templates/management/update.html
{% extends 'shared/base.html' %}

{% block title %}Management{% endblock title %}

{% block body %}
<!-- Main content -->
<main>
    <!-- Update form section -->
    <section class="container-fluid">
        <div class="container">
            <!-- Header -->
            <h1 class="display-4 text-center">Update Post</h1>

            <!-- Divider -->
            <hr class="border-dark w-50">

            <!-- Update form -->
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6">
                        <div class="lead">{{ form.project_name.label }}</div>
                        <div class="pb-1"></div>
                        {{ form.project_name }}
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.project_url.label }}</div>
                        <div class="pb-1"></div>
                        {{ form.project_url }}
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.author.label }}</div>
                        <div class="pb-1"></div>
                        {{ form.author }}
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.author_email.label }}</div>
                        <div class="pb-1"></div>
                        {{ form.author_email }}
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.is_in_progress.label }}</div>
                        <div class="pb-1"></div>
                        <div class="card">
                            <div class="card-body">{{ form.is_in_progess }} <span class="text-info">Are you done with
                                    the project</span></div>
                        </div>
                        <div class="pb-1"></div>
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-primary w-100 mt-2 mb-2"><i
                                        class="fa fa-plus-circle"></i> Create</button>
                            </div>
                            <div class="col-6">
                                <button type="reset" class="btn btn-warning w-100 mt-2 mb-2"><i
                                        class="fa fa-recycle"></i> Reset</button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <p class="text-center mt-1"><a href="{% url 'management:management-view' %}"
                                        class="btn-link">&leftarrow; Go to the dashboard</a></p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <span class="lead">{{ form.project_picture.label }}</span>
                        <div class="pb-1"></div>
                        <div class="custom-file">
                            {{ form.project_picture }}
                            <label class="custom-file-label">Select only 1 file</label>
                        </div>
                        <div class="pb-1"></div>

                        <span class="lead">{{ form.extra_information.label }}</span>
                        <div class="pb-1"></div>
                        <div class="custom-file">
                            {{ form.extra_information }}
                            <label class="custom-file-label">Optional, select only 1 file</label>
                        </div>
                        <div class="pb-1"></div>

                        <div class="lead">{{ form.project_description.label }}</div>
                        {{ form.project_description }}
                    </div>
                </div>
            </form>
        </div>
    </section>
</main>
{% endblock body %}