src/extra/urls.py
from django.urls import path
from .views import *

app_name = 'policies'

urlpatterns = [
    path('privacy/', privacy, name='privacy-policy'),
    path('terms-conditions/', terms_conditions, name='terms-and-conditions')
]

src/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('list/', projects, name='project-list')
]

src/management/urls.py
from django.urls import path
from .views import *

app_name = 'management'

urlpatterns = [
    path('', index, name='management-view'),
    path('create/', create, name='management-create'),
    path('delete/<int:id>', delete, name='management-delete'),
    path('update/<int:id>', update, name='management-update'),
]

src/website_development_portfolio/urls.py
""" Routes """

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='landing'),
    path('projects/', include('main.urls')),
    path('policies/', include('extra.urls')),
    path('management/', include('management.urls'))
]

# Static and media files routing
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "extra.views.page_not_found"
handler500 = "extra.views.server_error"

src/templates/shared/components/footer.html
{% extends 'shared/base.html' %}

{% block inline_css %}
<style>
    .divider {
        border-right: 1px solid white;
    }
</style>
{% endblock inline_css %}

{% block body %}

<!-- Footer component -->
<footer class="container-fluid bg-dark text-white pt-3 pb-3" id="footer">
    <div class="container">
        <div class="fixed-bottom"></div>
        <div class="row">
            <div class="col-6">
                <span class="pl-5"><span class="font-weight-bold">&copy;</span> Copyright 2020
                    <code>LokotamaTheMastermind</code></span>
            </div>
            <div class="col-6">
                <span class="float-right mr-5"><a href="{% url 'policies:terms-and-conditions' %}"
                        class="no-decoration link-color">Terms & Conditions</a><span class="divider ml-3"></span><a
                        href="{% url 'policies:privacy-policy' %}" class="ml-3 no-decoration link-color">Privacy
                        Policy</a></span>
            </div>
        </div>
    </div>
</footer>

{% endblock body %}

src/templates/shared/components/footer2.html
{% extends 'shared/base.html' %}

{% block inline_css %}
<style>
    .divider {
        border-right: 1px solid white;
    }
</style>
{% endblock inline_css %}

{% block body %}

<!-- Footer component -->
<footer class="container-fluid bg-dark text-white pt-3 pb-3 fixed-bottom">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <span class="pl-5"><span class="font-weight-bold">&copy;</span> Copyright 2020
                    <code>LokotamaTheMastermind</code></span>
            </div>
            <div class="col-6">
                <span class="float-right mr-5"><a href="{% url 'policies:terms-and-conditions' %}"
                        class="no-decoration link-color">Terms & Conditions</a><span class="divider ml-3"></span><a
                        href="{% url 'policies:privacy-policy' %}" class="ml-3 no-decoration link-color">Privacy
                        Policy</a></span>
            </div>
        </div>
    </div>
</footer>

{% endblock body %}

src/templates/shared/components/navbar.html
{% load static %}

{% block inline_css %}
<style>
    .no-decoration {
        text-decoration: none !important;
    }

    .animated-link {
        transition-timing-function: ease-in-out;
        transition-property: color, color;
        transition: .5s;
    }

    .animated-link:hover {
        border-bottom: 1px solid #ffffff !important;
    }

    .banner-header {
        border-bottom: solid #ffffff !important;
    }
</style>
{% endblock inline_css %}

{% block body %}
<!-- TODO: make this section responsive -->

<!-- Navbar component -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark container-fluid sticky-top fixed-top">
    <div class="container">
        <!-- Site logo -->
        <h3 class="navbar-brand banner-header"><img src="{% static 'shared/img/logo.png' %}" alt="Website Logo"
                width="30" height="30" class="img-thumbnail mr-2"><a href="/#top"
                class="no-decoration text-white text-sm-center">My
                Portfolio</a></h3>

        <!-- Main navbar -->
        <div class="navbar-collapse collaspe justify-content-center">

            <!-- Center links -->
            <div class="float-right">
                <a href="/#begin" class="text-white no-decoration animated-link mr-4">Home</a>
                <a href="/#about" class="text-white no-decoration animated-link mr-4">About</a>
                <a href="/#projects" class="text-white no-decoration animated-link mr-4">Projects</a>
                <a href="/#contact" class="text-white no-decoration animated-link">Contact</a>
            </div>

        </div>
        <!-- Right-aligned buttons -->
        <div class="dropdown ml-1">
            <a href="https://github.com/LokotamaTheMastermind/website-portfolio-django-project.git"
                target="_blank"><button class="btn btn-outline-success" type="button"><i
                        class="fab fa-github text-black-50"></i> Source
                    Code</button></a>
            <a href="{% url 'main:project-list' %}"><button class="btn btn-outline-primary" type="button"><i
                        class="fa fa-images text-white"></i> Projects List</button></a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'management:management-view' %}"><button class="btn btn-outline-danger"><i
                        class="fa fa-tasks"></i>
                    Management</button></a>
            {% endif %}
        </div>
</nav>
{% endblock body %}

src/templates/shared/components/navbar2.html
{% load static %}

{% block inline_css %}
<style>
    .no-decoration {
        text-decoration: none !important;
    }

    .animated-link {
        transition-timing-function: ease-in-out;
        transition-property: color, color;
        transition: .5s;
    }

    .animated-link:hover {
        border-bottom: 1px solid #ffffff !important;
    }

    .banner-header {
        border-bottom: solid #ffffff !important;
    }
</style>
{% endblock inline_css %}

{% block body %}
<!-- TODO: make this section responsive -->

<!-- Navbar component -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark container-fluid sticky-top fixed-top">
    <div class="container">
        <!-- Site logo -->
        <h3 class="navbar-brand banner-header"><img src="{% static 'shared/img/logo.png' %}" alt="Website Logo"
                width="30" height="30" class="img-thumbnail mr-2"><a href="/#top"
                class="no-decoration text-white text-sm-center">My
                Portfolio</a></h3>
        <!-- Collasped button on devices whose screen resolution is below laptops -->
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#homeNavbar"
            aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Right-aligned buttons -->
        <div class="dropdown ml-1">
            <a href="{% url 'management:management-create' %}"><button class="btn btn-outline-success" type="button"><i
                        class="fa fa-plus"></i> Create</button></a>
            <a href="/admin/" target="_blank"><button class="btn btn-outline-light"><i class="fa fa-database"></i>
                    Admin</button></a>
        </div>

</nav>
{% endblock body %}